import dayjs from 'dayjs';
import { IUserLite } from 'app/shared/model/user-lite.model';
import { IUserSettings } from 'app/shared/model/user-settings.model';
import { IUserReport } from 'app/shared/model/user-report.model';
import { IAssistanceTicket } from 'app/shared/model/assistance-ticket.model';
import { IMoneyPayout } from 'app/shared/model/money-payout.model';
import { ISubscriptionBundle } from 'app/shared/model/subscription-bundle.model';
import { ICreatorEarning } from 'app/shared/model/creator-earning.model';
import { IPaymentTransaction } from 'app/shared/model/payment-transaction.model';
import { IOfferPromotion } from 'app/shared/model/offer-promotion.model';
import { IPurchasedContent } from 'app/shared/model/purchased-content.model';
import { IPurchasedSubscription } from 'app/shared/model/purchased-subscription.model';
import { IWalletTransaction } from 'app/shared/model/wallet-transaction.model';
import { IPersonalSocialLinks } from 'app/shared/model/personal-social-links.model';
import { INotification } from 'app/shared/model/notification.model';
import { IUserAssociation } from 'app/shared/model/user-association.model';
import { IUserEvent } from 'app/shared/model/user-event.model';
import { IBookMark } from 'app/shared/model/book-mark.model';
import { IFeedback } from 'app/shared/model/feedback.model';
import { IDirectMessage } from 'app/shared/model/direct-message.model';
import { IChatRoom } from 'app/shared/model/chat-room.model';
import { IUserMention } from 'app/shared/model/user-mention.model';
import { IPostComment } from 'app/shared/model/post-comment.model';
import { IPostFeed } from 'app/shared/model/post-feed.model';
import { IPollVote } from 'app/shared/model/poll-vote.model';
import { IVideoStory } from 'app/shared/model/video-story.model';
import { ISingleDocument } from 'app/shared/model/single-document.model';
import { ICountry } from 'app/shared/model/country.model';
import { IState } from 'app/shared/model/state.model';
import { IHashTag } from 'app/shared/model/hash-tag.model';
import { IContentPackage } from 'app/shared/model/content-package.model';

export interface IUserProfile {
  id?: number;
  emailContact?: string;
  profilePhotoContentType?: string | null;
  profilePhoto?: string | null;
  coverPhotoContentType?: string | null;
  coverPhoto?: string | null;
  profilePhotoS3Key?: string | null;
  coverPhotoS3Key?: string | null;
  mainContentUrl?: string | null;
  mobilePhone?: string | null;
  websiteUrl?: string | null;
  amazonWishlistUrl?: string | null;
  lastLoginDate?: dayjs.Dayjs;
  biography?: string | null;
  isFree?: boolean | null;
  createdDate?: dayjs.Dayjs;
  lastModifiedDate?: dayjs.Dayjs | null;
  createdBy?: string | null;
  lastModifiedBy?: string | null;
  isDeleted?: boolean;
  userLite?: IUserLite;
  settings?: IUserSettings;
  makedReports?: IUserReport[] | null;
  receivedReports?: IUserReport[] | null;
  assistanceTickets?: IAssistanceTicket[] | null;
  withdraws?: IMoneyPayout[] | null;
  subscriptionBundles?: ISubscriptionBundle[] | null;
  earnings?: ICreatorEarning[] | null;
  payments?: IPaymentTransaction[] | null;
  planOffers?: IOfferPromotion[] | null;
  purchasedContents?: IPurchasedContent[] | null;
  purchasedSubscriptions?: IPurchasedSubscription[] | null;
  wallets?: IWalletTransaction[] | null;
  socialNetworks?: IPersonalSocialLinks[] | null;
  commentNotifications?: INotification[] | null;
  messageNotifications?: INotification[] | null;
  userMentionNotifications?: INotification[] | null;
  commentMentionNotifications?: INotification[] | null;
  ownAccountsAssociations?: IUserAssociation[] | null;
  createdEvents?: IUserEvent[] | null;
  bookMarks?: IBookMark[] | null;
  feedbacks?: IFeedback[] | null;
  sentMessages?: IDirectMessage[] | null;
  chats?: IChatRoom[] | null;
  mentions?: IUserMention[] | null;
  comments?: IPostComment[] | null;
  feeds?: IPostFeed[] | null;
  votedPolls?: IPollVote[] | null;
  videoStories?: IVideoStory[] | null;
  documents?: ISingleDocument[] | null;
  countryOfBirth?: ICountry | null;
  stateOfResidence?: IState | null;
  followeds?: IUserProfile[] | null;
  blockedLists?: IUserProfile[] | null;
  loyaLists?: IUserProfile[] | null;
  subscribeds?: IUserProfile[] | null;
  joinedEvents?: IUserEvent[] | null;
  blockedUbications?: IState[] | null;
  hashTags?: IHashTag[] | null;
  followers?: IUserProfile[] | null;
  blockers?: IUserProfile[] | null;
  awards?: IUserProfile[] | null;
  subscriptions?: IUserProfile[] | null;
  contentPackageTags?: IContentPackage[] | null;
}

export const defaultValue: Readonly<IUserProfile> = {
  isFree: false,
  isDeleted: false,
};
